#baseURL = 'https://based.cooking/'
baseURL = 'https://clamsen.github.io/cooking/'
languageCode = 'en-us'
title = 'Clamsen`s Cooking'
#theme = 'lugo'

[params]
  favicon = "/cooking/favicon.svg"
  stylesheet = "/cooking/style.css"
  indexarticles = 50
  taglist = true
  relatedtext = "Related:"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
